### ISSUE TITLE
Incorrect getOffers Example Code

### ISSUE THREAD

**Issue by bennetrj** [AdobeDocs/target.en#71]
Issue in help/c-implementing-target/c-implementing-target-for-client-side-web/adobe-target-getoffers-atjs-2.md

Hi Team,

The example which is mentioned under the title "Call getOffers() for all views" for fetching all views is missing the request object wrapper in it.

The one in the doc is this:-

adobe.target.getOffers({
prefetch: {
     views: []
   }
}
});

it should be like this.

adobe.target.getOffers({
   request : {
prefetch: {
     views: [{}]
   }
 }
});

**Comment by mtalbot29** [comment]
Fixed. Thanks for the catch!

**Comment by bennetrj** [comment]
@mtalbot29  I checked again and it seems it is still missing an object inside the views Array. 

it should be like this to fetch all view.

`adobe.target.getOffers({
    request: {
      prefetch: {
        views: [{}]
    }
  }
});`
